language: swift
osx_image: xcode11

before_install:
  - pod repo update
  - git submodule update --init --recursive
  
script:
  - xcodebuild -scheme MobileDB -workspace MobileDB.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
